- .github/workflows/test.yml
- rustfmt.toml
This is an unstable `rustfmt` option, so we switch to the nightly channel to make it take effect.
> Format imports with module granularity

- Cargo.toml
- src/bin/mdbook-gettext.rs
- src/bin/mdbook-xgettext.rs
The API changed a little from version 0.1.0.
The new release includes https://github.com/BrettDong/polib/pull/1, which means we can simplify the code that writes a new PO file.
> Update `polib` dependency to version 0.2.0

- Cargo.lock
> Update `Cargo.lock` after `polib` update

- Cargo.lock
- Cargo.toml
- src/bin/mdbook-gettext.rs
I first updated `toml` to 0.7.3, but this caused
error[E0631]: type mismatch in function arguments
--> src/bin/mdbook-gettext.rs:80:45
|
80   |     let po_dir = cfg.get("po-dir").and_then(Value::as_str).unwrap_or("po");
|                                    -------- ^^^^^^^^^^^^^
|                                    |        |
|                                    |        expected due to this
|                                    |        found signature defined here
|                                    required by a bound introduced by this call
|
= note: expected function signature `fn(&toml::value::Value) -> _`
found function signature `for<'a> fn(&'a toml::Value) -> _`
note: required by a bound in `Option::<T>::and_then`
It turned out I could remove the explicit dependency completely, …
> Update all dependencies

- README.md
The upstream issue (https://github.com/rust-lang/mdBook/issues/5) has been open since 2015.
> Link back to `mdbook` i18n issue

- Cargo.lock
- Cargo.toml
- src/bin/mdbook-gettext.rs
- src/bin/mdbook-xgettext.rs
- src/lib.rs
Before, we would extract text based on the byte offsets in the original document. As a consequence of this, the extracted text would look precisely like the original: the Markdown was copied directly from the original. In particular, text from a block quote would contain the leading ‘>’ characters and paragraphs in list items would contain leading whitespace.
Now, we instead extract text by grouping the Markdown parse events into those which should be translated and those who should be skipped. We use this in two ways:
- When extracting messages in ‘mdbook-xgettext’, we turn the translatable events back into Markdown. The structure of the document (headings, lists, block quotes, …) is no longer present in the extracted messages: only the text content itself it extracted.
- When …
> Implement fine-grained extraction of translatable text

- src/bin/mdbook-gettext.rs
- src/bin/mdbook-xgettext.rs
- src/lib.rs
This change makes the extracted messages ignore any wrapping done for readability of the Markdown source. So
This is a
paragraph.
and
This is a paragraph.
now becomes the same message in the PO file. This makes it possible for people to freely reformat the source files, without having to worry about invalidating existing translations.
Part of #19.
> Normalize soft breaks to space

- src/bin/mdbook-gettext.rs
- src/lib.rs
Before, `extract_messages` would turn a code block into text indistinguishable from a normal paragraph. This is bad since we would like `extract_messages` to be idempotent since that makes it easier to reason about normalization of the PO files.
> Extract code blocks as self-contained values

- Cargo.lock
- Cargo.toml
The crate comes with “watch” and “serve” features which are only necessary for the command line program. Since we use it as a library, we can simplify our dependency tree a bit like this.
> Remove unnecessary mdbook features

- src/bin/mdbook-gettext.rs
- src/lib.rs
When extracting events from a line of text, we get
&[
(1, Event::Start(Tag::Paragraph)),
(1, Event::Text("A line of text".into())),
(1, Event::End(Tag::Paragraph)),
],
This is problematic since the `Text` event has been wrapped in a paragraph. This is mostly harmless in regular text, but it destroys the formatting of tables since they cannot contain block-level events such as paragraphs.
This is now fixed by more carefully trimming the events we inject when translating.
> Fix table rendering

- src/bin/mdbook-i18n-normalize.rs
- src/lib.rs
The new binary will take an old PO file with existing translations as input. It runs `extract_messages` on every message, matches up the new messages, and outputs a normalized PO file. The normalized file maintains the old translations when possible.
How is this tested? I used the Korean translation of Comprehensive Rust as a starting point since it is the most complete translation at the moment. I ran the following commands
MDBOOK_OUTPUT='{"markdown": {}}' MDBOOK_BOOK__LANGUAGE=ko mdbook build -d markdown-ko
to generate Markdown using the current translation. I then ran
mdbook-i18n-normalize po/ko.po po/ko-norm.po
MDBOOK_OUTPUT='{"markdown": {}}' MDBOOK_BOOK__LANGUAGE=ko-norm mdbook build -d markdown-ko-norm
to generate Markdown using the normalized file. Before comparing the two …
> Add `mdbook-i18n-normalize` to convert existing PO files

- src/bin/mdbook-i18n-normalize.rs
This is a corner case found in some of the PO files in Comprehensive Rust.
> Handle normalization where old `msgid` disappears

- Cargo.lock
- Cargo.toml
- USAGE.md
- src/lib.rs
This is the beginning of support for handling special comments for translation, https://github.com/google/mdbook-i18n-helpers/issues/63
This adds support for adding a comment of the form: ``.  This will cause the system to skip the next message group that would otherwise be translated.
It adds a dependency to the regex crate to match for the comment skip pattern.
> Add support for skipping the next translation group

- src/bin/mdbook-gettext.rs
- src/bin/mdbook-i18n-normalize.rs
- src/lib.rs
This tries to automatically omit codeblocks that don't have what looks like translatable content.  For the moment, we check whether the body of a codeblock contains a "\"" or "//" substring, which is a heuristic for checking for literal strings or line comments.
> Automatically ignore codeblocks that don't have lit-strings or line comments.

- src/lib.rs
This adjusts the comment since we have a better understanding of the cause of the issue.
> Fix wording of test since the behavior is technically not a Markdown bug

- USAGE.md
- src/lib.rs
Some of the comments has more dashes than necessary — I kept the test cases that tested extra dashes on purpose.
> Simplify HTML comments

- Cargo.lock
- Cargo.toml
- src/bin/mdbook-xgettext.rs
The data is added to PO files automatically by `msgmerge`. This will in turn be used when publishing a translation: it allows us to know which sources goes into a given PO file.
Part of #16.
> Set POT-Creation-Date in newly generated POT files

- Cargo.toml
As I was following the testing instructions on https://github.com/google/mdbook-i18n-helpers/discussions/73 
when I stumbled on this: 
I fixed this error by specify the resolver version.
> Specify resolver types

- Cargo.lock
- i18n-helpers/Cargo.toml
- i18n-helpers/src/bin/mdbook-xgettext.rs
This will reduce churn between the output of `mdbook-xgettext` and `msgmerge`. See https://github.com/google/comprehensive-rust/pull/1245 for an example PR which would shrink with this feature.
Part of #32, but we still have differences in the way the messages themselves are wrapped.
> Wrap the source lines like `msgmerge` does

- .github/workflows/test.yml
- i18n-helpers/fuzz/Cargo.lock
Currently caching does not work for `fuzz` job which can be verified by looking at Github workflow outputs.
The main cause of the issue is the config `workspaces: fuzz -> target`. The fuzz target does not use a proper workspace but a separate crate. There is [a pending issue](https://github.com/rust-fuzz/cargo-fuzz/issues/345) discussing that.
The `rust-cache` action is executed in the root of the project and is not able to locate `fuzz` directory by workspace name.
I decided to list the directories to cache instead of relying on target dir detection which seems to work.
I also fixed the path `fuzz/corpus` to `i18n-helpers/fuzz/corpus`.
I adjusted the caching condition `save-if` to cache only on `main` builds. I think this makes sense because we don't need to cache PRs which might not get …
> Fix caching of `target` dir for `fuzz` project

- i18n-helpers/src/bin/mdbook-gettext.rs
- i18n-helpers/src/bin/mdbook-xgettext.rs
This first changes `mdbook-xgettext` so that formatting is preserved from the `SUMMARY.md` file.
Next, `mdbook-gettext` is changed to translate text from the `SUMMARY.md` file without formatting: this is necessary since `mdbook` strips formatting before sending the TOC to the preprocessor.
Fixes #66.
> Allow formatting in the `SUMMARY.md` file

- i18n-helpers/src/lib.rs
This is part of #105, the test demonstrates how we extract backslashes: `\` (a single backslash) in the Markdown file becomes `\\` (a backslash-escaped backslash) afterwards.
This is consistent with the Commonmark spec, which says that a backslash-escaped backslash is how you can represent a backslash in the document: https://spec.commonmark.org/0.30/#backslash-escapes.
However, it can lead to problems if the LaTeX preprocessor doesn’t handle `\\` in the Markdown file as a `\`.
> Test `extract_messages` with backslashes

- .github/workflows/test.yml
When addressing [this comment](https://github.com/google/mdbook-i18n-helpers/pull/104#discussion_r1375514472)
> `You should at least trip the return which is not necessary here.`
I noticed Clippy warnings such as `warning: unneeded "return" statement` and others like [this](https://github.com/google/mdbook-i18n-helpers/actions/runs/6686046766/job/18164991850?pr=104) do not produce  non-zero status code which means the PR won't fail.
I am adding `-D clippy::all` in order to deny all default warnings to fail PRs.
Also adding a separate call to `cargo clippy` in directory `i18n-helpers/fuzz` because it is considered to be a separate workspace.
> Deny all default Clippy errors/warnings in github workflow

- i18n-helpers/src/lib.rs
This just calls a library function instead of doing the test by hand.
> Simplify filtering translated messages

- .github/workflows/test.yml
- i18n-helpers/src/lib.rs
This skips empty messages and messages consisting of whitespace only.
Fixes #64.
> Skip extracting whitespace-only messages

- .github/workflows/test.yml
This should have no effect for us since we only use default features.
> Bump checkout action to v4

- Cargo.lock
- i18n-helpers/Cargo.toml
- i18n-helpers/USAGE.md
- i18n-helpers/fuzz/Cargo.lock
- i18n-helpers/fuzz/fuzz_targets/group_events.rs
- i18n-helpers/src/gettext.rs
- i18n-helpers/src/lib.rs
- i18n-helpers/src/normalize.rs
Fixes #95 
This PR adds codeblock parsing support to extract only strings and comments.
> Extract only strings and comments from codeblock

- .github/workflows/test.yml
This expands our testing to test extracting text from both the Rust Book and Comprehensive Rust. We only check the format of the generated POT file right now, but we might be able to expand this to other checks later.
> Test extracting text from multiple books

- Cargo.lock
- README.md
- i18n-helpers/CHANGELOG.md
- i18n-helpers/Cargo.toml
- i18n-helpers/README.md
- i18n-helpers/fuzz/Cargo.lock
This release changes how code blocks are treated: we now only extract literal strings and comments. Other parts of the code block is ignored. This vastly improves the experience when translating books with many code samples. We will add more controls (#76) for this in the future.
> This is a breaking change: if you translate strings and comments in your code blocks, then you should [run `mdbook-i18n-normalize`](i18n-helpers/USAGE.md) to migrate them automatically!
- #111
- #109
- #100
- #93
> Release 0.3.0

- i18n-helpers/src/lib.rs
We drop some unnecessary escapes from the raw strings.  This is to clean up some lint warnings from Clippy.
> Drop unnecessary hashes from raw strings.

- i18n-helpers/src/bin/mdbook-xgettext.rs
- i18n-helpers/src/lib.rs
- i18n-helpers/src/normalize.rs
Noticed by @henrif75 in https://github.com/google/comprehensive-rust/issues/317.
Part of #32 and a followup to #93.
> Wrap source lines in `mdbook-i18n-normalize`

- i18n-helpers/src/directives.rs
- i18n-helpers/src/lib.rs
This moves the comment directive parsing to a separate module and adds two features:
* Customizable prefix for the directive.   It defaults to "i18", but to maintain compatibility, overridden with "mdbook-xgettext"  in its current usage.
* Can parse translator comments.
This is preparatory work to thread this state during message extraction.
> Add translator comment parsing

- Cargo.lock
- mdbook-tera-backend/Cargo.toml
- mdbook-tera-backend/src/tera_renderer/renderer.rs
Instead of hard-coding a large JSON string, we can use the real infrastructure instead and setup an actual book, load it, and use it to generate a context.
Using the actual dependency is preferable to using a mocked dependency since it allows us to test against the real implementation.
> Create `RenderContext` using a real book

- i18n-helpers/src/lib.rs
Codeblock which contains ```` ``` ```` will be like below:
`````markdown
````markdown
```rust
let a = 0;
```
````
`````
But the output of mdbook-i18n-helpers seems to be broken like below:
`````markdown
```markdown
```rust
let a = 0;
```
```
`````
This is because codeblock token count is fixed as 3 in `reconstruct_markdown`.
This PR adds to check the appropriate codeblock token count.
> Fix codeblock in codeblock

- i18n-helpers/CHANGELOG.md
The CHANGELOG was moved around in #116, but I forgot to update all the relevant links.
> Fix links to the USAGE file

- .github/workflows/test.yml
[cargo-llvm-cov](https://github.com/taiki-e/cargo-llvm-cov) is used for generating coverage reports.
The library supports different report types which all have their own pros and cons:
* `--lcov` - reports in `lcov` format which are supported by Codecov. They support only line level coverage and will not provide any info on regions. Example report can be seen [here](https://app.codecov.io/gh/kdarkhan/mdbook-i18n-helpers/commit/f8e7bb95e74031e9a2276defda8b99ece4046cc8/tree).
* `--codecov` - Codecov's custom format which somewhat supports region coverage but not fully. Example report can be seen [here](https://app.codecov.io/gh/kdarkhan/mdbook-i18n-helpers/commit/b3384aa77c7ea7172324a292fcc12568ed5511fc/tree). Notice that some lines are colored in yellow - which means they are partially …
> Implement coverage reports using codecov

- .github/workflows/test.yml
This is an attempt at fixing 503 errors which occur sometimes during coverage uploads
https://github.com/google/mdbook-i18n-helpers/issues/148.
> Use project specific codecov token for coverage reports

- i18n-helpers/src/lib.rs
Before we would load and deserialize the `syntect` syntax trees (Sublime Text syntax definitions) on every call. We now cache this read-only data.
Before, `mdbook build` took 1.44 s, now it takes 0.56 s instead. I started looking in to optimizing this because I'm considering making `mdbook-xgettext` an (optional) plugin in `book.toml` for Comprehensive Rust. This will imply that we run the plugin on every `mdbook build` — at least for people like me who have the plugin installed.
> Cache `SyntaxSet` between `parse_codeblock` calls

- .github/workflows/test.yml
- Cargo.toml
- i18n-helpers/Cargo.toml
- i18n-helpers/fuzz/Cargo.toml
- mdbook-tera-backend/Cargo.toml
Before, we did not actually run tests for `mdbook-tera-backend`. Now that the crate is a default workspace member, we will automatically run tests and Clippy for it too.
This also makes it easier to apply the same lints at home as in CI: just run `cargo clippy` with a nightly Rust compiler. The `lints` table should [become stable with Rust 1.74](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#lints).
> Ensure we run tests and Clipply on entire workspace

- i18n-helpers/src/gettext.rs
- i18n-helpers/src/lib.rs
This PR fixes wrong token count in code block reported at #150.
> Fix code block token count

- Cargo.lock
- i18n-helpers/Cargo.toml
- i18n-helpers/src/lib.rs
The logic of `check_code_block_token_count` was merged into pulldown-cmark-to-cmark crate.
> Remove check_code_block_token_count function

- .github/workflows/coverage-report.yml
- .github/workflows/test.yml
This addresses #148. Codecov coverage report upload are not stable. The suggested solution is to use
per project secret. This project have that enabled but it is not usable for pull request workflows triggered from forks. Due to Github's security restrictions, only PRs based on local branches have access to secrets.
This PR amends the existing workflow by not pushing the reports to Codecov. The reports are instead uploaded to Github artifacts (the artifacts are stored for 90 days by default).
Then a new workflow is introduced which executes after every successful execution of the existing workflow. It downloads the artifact and uploads the report to Codecov using the security token.
> Make codecov report use secret

- .github/workflows/coverage-report.yml
I want to temporarily start logging `github.context` object. It seems the coverage reports sometimes do not get correct [overrides](https://github.com/google/mdbook-i18n-helpers/blob/33fec9577e55e337aee77604da0954285fc56449/.github/workflows/coverage-report.yml#L59-L60).
Because of that, Codecov reports appear as attached to `main` instead of the correct PR.
I tried to reproduce this issue by creating PRs against my fork but did not have any luck.
Interestingly, it does seem to work for some PRs but broken for others.
As I understand, `context.payload` JSON object will have the same content as `github.event` expression in YAML.
> Log github.context to investigate missing coverage reports

- .github/dependabot.yml
The initial version defined groups only for cargo
deps. Because of that, we have 2 separate PRs related to `github-actions`. This ensures that grouping logic works for all deps.
> Make dependabot grouping work on all update types

- .github/workflows/coverage-report.yml
This is causing coverage reports fail. Reverting this now until we have a working solution
d76153d 'Bump codecov/codecov-action from 3 to 4 (#169)'
Relevant links:
* https://github.com/google/mdbook-i18n-helpers/issues/173
* https://github.com/codecov/feedback/issues/263
> Revert cocecov-action upgrade

- fuzz/fuzz_targets/xgettext.rs
- i18n-helpers/USAGE.md
- i18n-helpers/src/bin/mdbook-xgettext.rs
- i18n-helpers/src/xgettext.rs
Hey all! This is a PR in relation to #67 to split the pot file depending on
the specified depth. Another PR will be submitted to change `gettext`
to merge a directory of `pot` files.
- Add an input param to `xgettext` to take in an integer for the depth to
split the POT file. Remove the input-file param
- Mimics the same structure as the SUMMARY file for the Book
- Revise the helper fn to create a render ctx for tests. Now, it can
create on-the-fly directories if the markdown file exists in a
sub-directory
- Test the new split catalog function with different possible inputs
> Split POT file depending on specified depth

- .github/workflows/coverage-report.yml
With the issues https://github.com/codecov/feedback/issues/263 and https://github.com/codecov/codecov-action/issues/1287 resolved, we can upgrade to v4 again.
This fixes https://github.com/google/mdbook-i18n-helpers/issues/173
> Upgrade codecov-action to v4

- Cargo.lock
- i18n-helpers/Cargo.toml
- i18n-helpers/src/gettext.rs
- i18n-helpers/src/lib.rs
- i18n-helpers/src/normalize.rs
- i18n-helpers/src/xgettext.rs
The latest version of `pulldown-cmark-to-cmark` now supports `pulldown-cmark`. This should allow us to upgrade both dependencies.
Had to adjust TagEnd handling and change some types to fix the build failures.
Information on breaking changes in `pulldown-cmark` is available [here](https://github.com/pulldown-cmark/pulldown-cmark/releases). Not sure if I am missing anything. I hope that the tests we have are extensive enough to catch any issues.
> Upgrade pulldown-cmark to 0.10.3

- Cargo.lock
This fixes the compilation issue in `time` crate
by upgrading it from 0.3.30 to 0.3.36.
Failure example https://github.com/google/mdbook-i18n-helpers/actions/runs/9171277226/job/25215262973.
If less diff is desired, I could update only `time` by `cargo update time` but probably we can update all minor versions.
> Execute `cargo update`

- .github/workflows/test.yml
- i18n-helpers/src/gettext.rs
- i18n-helpers/src/lib.rs
- i18n-helpers/src/normalize.rs
Fixes #125 by keeping inline HTML tags in the translation text group but skip block level HTML tags.
This is possible with the upgrade of pulldown-cmark in #183
> Keep Inline HTML tags in the translated text group while ignoring block level HTML tags

- i18n-helpers/src/xgettext.rs
`strip_link` seems to remove all links from catalog.
According to the comment, it should be applied to summary only.
https://github.com/google/mdbook-i18n-helpers/blob/71b4cc5d1c0cf0db14f2c264ddccee401b8e36c6/i18n-helpers/src/xgettext.rs#L145-L149
Closes #202
> Remove unnecessary strip_link

- Cargo.lock
- i18n-helpers/CHANGELOG.md
- i18n-helpers/Cargo.toml
Hotfix release to include changes from https://github.com/google/mdbook-i18n-helpers/pull/203
> Bump mdbook-i18n-helpers version to 0.3.4

- Cargo.lock
- i18n-report/Cargo.toml
- i18n-report/README.md
- i18n-report/src/main.rs
- i18n-report/src/stats.rs
The report looks like this:
```
Counts are "translated (fuzzy, fuzzy untranslated) / total"
Removed bn: 752 (54, 1) / 3761, creation date 2024-03-03T20:37:57+05:30
Added fo: 568 (178, 1) / 3651, creation date 2024-01-24T13:24:49+01:00
Changed ro: 1032 (2731, 0) / 3763, creation date 2024-05-15T20:58:33+03:00 -> ro: 1018 (2731, 0) / 3749, creation date 2024-05-15T20:58:33+03:00
```
The intention is that this can be used from a GitHub action to show a summary of translation changes on PRs.
> Add i18n-report mode to show diff between two sets of translations

- Cargo.lock
- i18n-helpers/Cargo.toml
- i18n-helpers/src/normalize.rs
Fixes #117.
Advances POT-Creation-Date by 1 minute rather than 1 second as @mgeisler suggested as it seems like the date format does not include seconds for some reason: https://www.gnu.org/software/trans-coord/manual/gnun/html_node/PO-Header.html
```
"POT-Creation-Date: 2008-02-06 16:25-0500\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
```
> Advance POT-Creation-Date by 1 minute on normalization

- i18n-helpers/src/xgettext.rs
Related to #171.
While trying to refresh the Spanish translation of Comprehensive Rust, @henrif75 noticed that the `messages.pot` file I generated had line numbers that shouldn't be there (see https://github.com/google/comprehensive-rust/issues/2120).
Digging around in the code, I noticed that the `xgettext` code was ignoring the granularity for sub-chapters. This PR fixes that!
> Make xgettext respect granularity for sub-chapter messages

- .github/dependabot.yml
We are not super dependent on using the latest patch releases of every crate, so a monthly update frequency should be more than enough.
Note that we still get PRs if/when there is a [security update](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval).
> Lower dependabot frequency to monthly

- Cargo.lock
- i18n-helpers/Cargo.toml
- i18n-helpers/src/lib.rs
* Upgrades pulldown-cmark-to-cmark
* Adjust tests for new way reference links are handled
This supersedes https://github.com/google/mdbook-i18n-helpers/pull/233.
Tests had to be adjusted because new version of the library retains more info from reference links. Reference links are no longer replaced with full URLs. We can probably make some manual adjustments to reference link handling in order to retain the old behavior but I think the new way should work better.
> Pulldown cmark to cmark 17.0.0 upgrade

- Cargo.lock
- i18n-helpers/CHANGELOG.md
- i18n-helpers/Cargo.toml
This is necessary to support Rust 2024 edition.
> Prepare mdboook-i18n-helpers for 0.3.6 release.
